name: Close Milestone

on:
  pull_request:
    types: [closed]

jobs:
  close-milestone:
    name: Close Milestone
    runs-on: ubuntu-latest
    steps:
    - name: Run Close Milestone Action
      id: run-close-milestone-action
      uses: DanS01/Close-Milestone-Action@v1
      with:
        secrets-token: ${{ secrets.GITHUB_TOKEN }}
